/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MovementAssessmentRouteImport } from './routes/movement-assessment'
import { Route as NewScreeningRouteImport } from './routes/new-screening'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MovementAssessmentRoute = MovementAssessmentRouteImport.update({
  id: '/movement-assessment',
  path: '/movement-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const NewScreeningRoute = NewScreeningRouteImport.update({
  id: '/new-screening',
  path: '/new-screening',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/movement-assessment': typeof MovementAssessmentRoute
  '/new-screening': typeof NewScreeningRoute
  '/patients': typeof PatientsRoute
  '/referrals': typeof ReferralsRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/movement-assessment': typeof MovementAssessmentRoute
  '/new-screening': typeof NewScreeningRoute
  '/patients': typeof PatientsRoute
  '/referrals': typeof ReferralsRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/movement-assessment': typeof MovementAssessmentRoute
  '/new-screening': typeof NewScreeningRoute
  '/patients': typeof PatientsRoute
  '/referrals': typeof ReferralsRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/movement-assessment'
    | '/new-screening'
    | '/patients'
    | '/referrals'
    | '/results'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/movement-assessment'
    | '/new-screening'
    | '/patients'
    | '/referrals'
    | '/results'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/movement-assessment'
    | '/new-screening'
    | '/patients'
    | '/referrals'
    | '/results'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MovementAssessmentRoute: typeof MovementAssessmentRoute
  NewScreeningRoute: typeof NewScreeningRoute
  PatientsRoute: typeof PatientsRoute
  ReferralsRoute: typeof ReferralsRoute
  ResultsRoute: typeof ResultsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movement-assessment': {
      id: '/movement-assessment'
      path: '/movement-assessment'
      fullPath: '/movement-assessment'
      preLoaderRoute: typeof MovementAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-screening': {
      id: '/new-screening'
      path: '/new-screening'
      fullPath: '/new-screening'
      preLoaderRoute: typeof NewScreeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MovementAssessmentRoute: MovementAssessmentRoute,
  NewScreeningRoute: NewScreeningRoute,
  PatientsRoute: PatientsRoute,
  ReferralsRoute: ReferralsRoute,
  ResultsRoute: ResultsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
